learning_site/courses/urls.py
from django.conf.urls import include, url
from . import views
urlpatterns = [
	url(r'^$', views.course_list, name='list'),
	url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)', views.step_detail, name='step'),
	url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
]

learning_site/learning_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.hello_world),
    url(r'^suggest$', views.suggestion_view, name='suggestion'),
    url(r'^courses/', include('courses.urls', namespace='courses')),
]

urlpatterns += staticfiles_urlpatterns()

learning_site/courses/models.py
from django.db import models

# Create your models here.

class Course(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	title = models.CharField(max_length=255)
	description = models.TextField()

	def __str__(self):
		return self.title

class Step(models.Model):
	title = models.CharField(max_length=255)
	description = models.TextField()
	content = models.TextField(blank=True, default='')
	order = models.IntegerField(default=0)
	course = models.ForeignKey(Course)

	class Meta:
		ordering = ['order', ]

	def __str__(self):
		return self.title

learning_site/learning_site/forms.py
from django import forms

class SuggestionForm(forms.Form):
	name = forms.CharField()
	email = forms.EmailField()
	suggestion = forms.CharField(widget=forms.Textarea)

learning_site/courses/views.py
from django.shortcuts import get_object_or_404, render
from .models import Course, Step
from django.http import HttpResponse
# Create your views here.

# def courses_list(request):
# 	courses = Course.objects.all()
# 	output = ', '.join([str(course) for course in courses])
	
# 	return HttpResponse(output)

def course_list(request):
	courses = Course.objects.all()
	email = 'questions@learning-site.com'
	context = {'courses': courses, 'email': email}
	return render(request, 'courses/course_list.html', context)

def course_detail(request, pk):
	# course = Course.objects.get(pk = pk)
	course = get_object_or_404(Course, pk=pk)
	return render(request, 'courses/course_detail.html', {'course': course})

def step_detail(request, course_pk, step_pk):
	step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
	return render(request, 'courses/step_detail.html', {'step':step})

learning_site/learning_site/views.py
from django.http import HttpResponse
from django.shortcuts import render
from . import forms

def hello_world(request):
	return render(request, 'home.html')

def suggestion_view(request):
	form = forms.SuggestionForm()
	return render(request, 'suggestion_form.html', {'form': form})

learning_site/courses/templates/courses/course_detail.html
{% extends 'layout.html' %}
{% load humanize course_extras %}
{% block title %}
{{ course.title }}
{% endblock title %}

{% block content %}
<article>
	<h2>{{course.title}}</h2>
	{{ course.description|markdown_to_html }}
	<p>There are {{ course.step_set.count|apnumber }} of Step{{ course.step_set.count|pluralize }} In This course: {{ course.step_set.all|join:", " }}</p>
	<section>
		{% for step in course.step_set.all %}
		<h2><a href="{% url 'courses:step' course_pk=step.course.pk step_pk=step.pk %}">{{ step.title }}</a></h2>
		{{ step.description }}
		{% endfor %}
	</section>
</article>
{% endblock %}

learning_site/courses/templates/courses/course_list.html
{% extends 'layout.html' %}
{% load static from staticfiles %}
{% block static %}
<link rel='stylesheet' href="{% static 'courses/css/courses.css' %}">
{% endblock %}
{% block content %}
<div class='cards'>
	{% for course in courses %}
	<div class=card>
		<header><a href="{% url 'courses:detail' pk=course.pk %}">{{course.title}}</a></header>
		<div class='card-copy'>
		{% if course.description|wordcount <= 5 %}
			{{course.description}}
		{% else %}
			{{ course.description|truncatewords:5 }}
			<a href="{% url 'courses:detail' pk=course.pk %}">Read More</a>
		{% endif %}
		<div>Created On: {{ course.created_at|date:'m/d/y, H:i' }}</div>
		<!-- <div>Have A Questions? Contact Us:<a href="mailto:{{email}}">{{email}}</a></div> -->
		<div>Have A Questions? Contact Us: {{ email|urlize }}</div>
		</div>
	</div>

	{% endfor %}
</div>
{% endblock %}

learning_site/courses/templates/courses/course_nav.html
{% for course in courses %}
	<div><a href="{% url 'courses:detail' pk=course.pk %}" >{{ course.title }}</a></div>
{% endfor %}

learning_site/courses/templates/courses/step_detail.html
{% extends 'layout.html' %}
{% load course_extras %}

{% block title %} {{ step.course.title }}-{{step.title}} {% endblock %}

{% block content %}
<article>
	<h2><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></h2>
	<h4>{{ step.title }}</h4>
	{% with con=step.content %}
	{{ con|linebreaks }}Content:{{ con|wordcount }}. Estimated Time To Complete {{ con|wordcount|time_estimate }} Minute{{ con|wordcount|time_estimate|pluralize }}
	{% endwith %}
</article>
{% endblock %}

learning_site/templates/home.html
{% extends 'layout.html' %}

{% block title %}

{% endblock %}

{% block content %}
<h2>Hello from home page!</h2>
{% endblock %}

<h1>Welcome!</h1>

learning_site/templates/layout.html
{% load static from staticfiles %}
{% load course_extras %}
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link rel='stylesheet' href="{% static 'css/layout.css' %}">
		{% block static %} {% endblock %}
	</head>
	<body>
	
	<div class='site-container'>
		<div>{% nav_courses_list %}
		<nav>
			<a href="{% url 'views.hello_world' %}">Home</a>
			<a href="{% url 'courses:list' %}">Courses</a>
		</nav>
	<p>Don't Miss Our Latest Course, {% newest_course %}!</p>
	{% block content %}
	<h2>Hello From Layout!</h2>
	{% endblock content %}
	
	</div>
	</body>
</html>

learning_site/templates/suggestion_form.html
{% extends 'layout.html' %}

{% block title %}
 Have an Idea!
{% endblock %}

{% block content %}
<form action='' method='POST'>
	{{ form.as_p }}
	{% csrf_token %}
	<input type='submit'>
</form>
{% endblock %}

<h1>Welcome!</h1>